### ISSUE TITLE
是否能从文章中拖动块到白板或者excalidraw中？

### ISSUE THREAD

**Issue by wwjCMP** [cycsd/obsidian-card-note#1]

**Comment by cycsd** [comment]
請問你的塊是指什麼呢?

目前有支援的有

- 可摺疊區塊
- markdown 語法區塊
  ex: paragraph、list ...

都可藉由拖動區塊的第一列就能直接將整個區塊拖曳到你使用的白板中,

即使沒有支援的區塊 (ex: table 因為obsidian 有特殊處理過),

也可以藉由滑鼠或鍵盤按住shift 選擇你想要的文字後,

在將其拖動至你的白板中

**Comment by wwjCMP** [comment]
> 請問你的塊是指什麼呢?
> 
> 目前有支援的有
> 
> * 可摺疊區塊
> * markdown 語法區塊
>   ex: paragraph、list ...
> 
> 都可藉由拖動區塊的第一列就能直接將整個區塊拖曳到你使用的白板中,
> 
> 即使沒有支援的區塊 (ex: table 因為obsidian 有特殊處理過),
> 
> 也可以藉由滑鼠或鍵盤按住shift 選擇你想要的文字後,
> 
> 在將其拖動至你的白板中

那就是我这边出bug了，可以拖动块，但不能将其放到白板和excalidraw中

**Comment by wwjCMP** [comment]
发现问题所在了，不能拖动到弹出窗口中的白板或excalidraw。

**Comment by cycsd** [comment]
新版本 [0.5.0](https://github.com/cycsd/obsidian-card-note/releases/tag/0.5.0) 

已經可以在彈出窗口拖動區塊囉，

你可以再更新至新版後嘗試使用看看是否符合你的使用習慣。

**Comment by wwjCMP** [comment]
> 新版本 [0.5.0](https://github.com/cycsd/obsidian-card-note/releases/tag/0.5.0)
> 
> 已經可以在彈出窗口拖動區塊囉，
> 
> 你可以再更新至新版後嘗試使用看看是否符合你的使用習慣。

挺好，我有个问题，为什么只把这个功能限定在白板和excalidraw，而不允许在md文件之间进行拖放

**Comment by cycsd** [comment]
主要是因為個人精力有限，

且我認為在md文件之間進行拖放比較偏向編輯器的基本功能了，

這個功能如果能由 Obsidian 官方提供最好，能有比較少的 Bug 且功能可以比較全面，

其次是依個人使用 Notion 的經驗，在編輯器中拖拉區塊的功能，很少是在我整理思緒的時候需要用到，

用到的時機通常是在最後進行版面調整的時候使用，且偵測的擺放位置常常不是我想要的效果，

更多的時候用剪下貼上就可以達到需求，

而在同一份文件內拖拉的話， Obsidian 內更有 [keyshots](https://github.com/KrazyManJ/obsidian-keyshots?tab=readme-ov-file) 這類的編輯工具，其實已經比拖拉還要實用了，只是需要習慣使用鍵盤，

因此目前暫時不會支援在 md 文件之間進行拖放的功能，

當然，如果之後有足夠的能力跟時間，且官方還是沒有支援相關功能的話，

不排除會嘗試開發看看，謝謝。
