### ISSUE TITLE
No Link Option

### ISSUE THREAD

**Issue by jowibou** [cycsd/obsidian-card-note#2]
The link icon and action is not available to me in the modal, the only possible options are to cut the text or create a new note.

**Comment by jowibou** [comment]
This seems to have fixed itself. Link has returned. Any idea what happened?

**Comment by cycsd** [comment]
The "Link" is a special feature provided by Obsidian for the markdown file. This plugin uses the Obsidian file metadata cache to detect whether there are link sections. Therefore, if you encounter the two situations as described below, it is normal not to see the link option in the model.

1. You are in the Canvas text node. (no file can be linked)
2. You drag the block that you just wrote. (you need to wait for seconds to let Obsidian process the metadata cache)

If you encounter issues outside of these situations, please let me know. Thank you
