### ISSUE TITLE
Link to extracted card

### ISSUE THREAD

**Issue by macin** [cycsd/obsidian-card-note#3]
Hi, I love the plugin. This is what I was saerching for so big kudos! I just have one question, and this would have made a great deal easier to work with the plugin ... is there a way to  auto create a link to the card I cut from?
If that was possible, then I could split my big content card to multiple smaller cards and keep the relation indicating where the small cards came from...

**Comment by cycsd** [comment]
Thanks for your feedback.
I have thought about developing this function.
But later I felt that this function was too repetitive with the [BackLinks](https://help.obsidian.md/Plugins/Backlinks) function of obsidian.
When we create a new note with this plugin, an internal link to the new note will also be left in the original note, so you can use [BackLinks](https://help.obsidian.md/Plugins/Backlinks) function to easily find the relation between the new note and the original note, this is also a core feature of obsidian, and it seems to be the place where most people view the links related to notes.
If you still feel that you need such a function,
Could you explain in detail why you do not want to use Obsidian's [BackLinks](https://help.obsidian.md/Plugins/Backlinks) function but want to leave a link in a new note?
And if there was such a function, would you like to place the link to the origin note at the beginning or end of the new note?
Or place it in [note properties](https://help.obsidian.md/Editing+and+formatting/Properties)?
This could let me re-evaluate whether to implement such a function and meet the needs of users.
Thank you!

**Comment by macin** [comment]
Hi, video is worth 1000 words ? :) I've recorded my idea of what I wish I was able to achieve.
Please take a look

https://youtu.be/xSMXLu69b6c?si=WrJPUhWB8sMEyG-9

And I think I was not clear. I did not mean the link in an obsidian linking meaning. I just meant an arrow between nodes on canvas :)

**Comment by macin** [comment]
@cycsd did you have a chance to take a look at the worfklow I shared? Does it make sense now?

**Comment by cycsd** [comment]
Sorry for replying so late.
I have updated [a new version](https://github.com/cycsd/obsidian-card-note/releases/tag/1.1.0) for auto-link.
Hope you enjoy this update and give me more feedback, thank you.
