### ISSUE TITLE
I want to replace the Broken Heart Symbol (appeard in the gutter) with my own

### ISSUE THREAD

**Issue by Farrukhw** [cycsd/obsidian-card-note#8]
How can I change the Drag Symbol appearing the gutter (currently it is Red Broken Heart)?
And from where can I drag symbols to this dialog?

**Comment by cycsd** [comment]
You can replace the Drag Symbol with text or [eomji](https://en.wikipedia.org/wiki/Emoji) in the plugin's settings.
Simply choose your preferred emoji and paste it into the text box.
